name: Build and Release

on:
  push:
    tags:
      - 'v*' # Срабатывает только на теги (v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore GameServer

    - name: Build
      run: dotnet build GameServer --no-restore --configuration Release

    - name: Publish
      run: dotnet publish GameServer/GameServer.csproj -c Release -o ./publish

    - name: Install EF Tool
      run: dotnet tool install --global dotnet-ef --version 8.*

    - name: Build EF Migration Bundle
      run: |
        cd GameServer
        dotnet ef migrations bundle --self-contained -r linux-x64 -o ../publish/efbundle

    - name: Zip Release
      run: |
        cd publish
        zip -r ../GameServer.zip .

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: GameServer.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}